### ISSUE TITLE
Does not seem to work with JS/CSS files in webpack2

### ISSUE THREAD

**Issue by Ciantic** [cqqccqc/webpack-utf8-bom#3]
For me this does not work with webpack2 and JS/CSS files, but it does work with the HTML file produced by HtmlWebpackPlugin.

**Comment by Ciantic** [comment]
Looks like it can't recgonize JS/CSS files when they contain a query string, e.g.:

vendors.js?1499202230271

Which is a common way to cache busting.

**Comment by Ciantic** [comment]
This works:

new BomPlugin(true, /\.(html|htm|css|js|map)/)

**Comment by cqqccqc** [comment]
@Ciantic I will update README file
